spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none
  devtools:
    livereload:
      enabled: true
  #datasource exists in private layer (it has been gitignore)
  profiles:
    active: private

logging:
  level:
    root: debug