spring:
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        use-new-id-generator-mappings: false
        use_sql_comments: true
        format_sql: true
        show_sql: true

  devtools:
    livereload:
      enabled: true
  #datasource exists in private layer (it has been gitignore)
  profiles:
    active: private

logging:
  level:
    root: info